
BIN=../guide/bin

tool-span:
	$(BIN)/makeToolSpan */index.md

unix-span:
	$(BIN)/makeUnixSpan */index.md

option-span:
	$(BIN)/makeOptionSpan */index.md

rep-span:
	$(BIN)/makeRepSpan */index.md

misc:
	$(BIN)/miscCleanup */index.md

headings:
	$(BIN)/convertHeading */index.md

spaces:
	$(BIN)/cleanSpaces */index.md

