
BIN=bin

all:
	@echo "Read the contents of the Makefile for make targets."

tool-span:
	$(BIN)/makeToolSpan ch??/index.md

unix-span:
	$(BIN)/makeUnixSpan ch??/index.md

option-span:
	$(BIN)/makeOptionSpan ch??/index.md

rep-span:
	$(BIN)/makeRepSpan ch??/index.md

misc:
	$(BIN)/miscCleanup ch??/index.md

headings:
	$(BIN)/convertHeading ch??/index.md

spaces:
	$(BIN)/cleanSpaces ch??/index.md


